# Generated by Django 4.1.2 on 2022-10-17 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='firsname',
            new_name='firstname',
        ),
    ]
